#!/usr/bin/env python3
"""Generate single Word doc for Experiments 2-8 in the required format."""

from pathlib import Path
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT

BASE = Path("/home/mani-arch/Desktop/FSD lab/fullstack-web-lab")
OUT = BASE / "documents"
OUT.mkdir(exist_ok=True)

def add_code_block(doc, label, code_lines, font_size=12):
    p = doc.add_paragraph()
    r = p.add_run(label)
    r.bold = True
    r.font.size = Pt(14)
    r.font.name = "Cambria"
    p.paragraph_format.space_before = Pt(14)
    p.paragraph_format.space_after = Pt(8)
    p2 = doc.add_paragraph()
    p2.paragraph_format.space_before = Pt(0)
    p2.paragraph_format.space_after = Pt(8)
    p2.paragraph_format.line_spacing = Pt(18)
    for line in code_lines:
        r = p2.add_run(line + "\n")
        r.font.name = "Cambria"
        r.font.size = Pt(font_size)

EXPS = [
    {
        "num": 2,
        "title": "CREATE A WEB APPLICATION TO MANAGE THE TO-DO LIST OF USERS",
        "desc": "WHERE USERS CAN LOGIN AND MANAGE THEIR TO-DO ITEMS",
        "marks": "9665",
        "files": [
            ("INDEX.HTML :", [
                '<!DOCTYPE html>',
                '<html>',
                '<head>',
                '    <title>TO-DO List</title>',
                '</head>',
                '<body>',
                '<div class="container">',
                '    <div id="loginBox">',
                '        <h1>TO-DO List</h1>',
                '        <h2>Login</h2>',
                '        <input type="text" id="username" placeholder="Username">',
                '        <input type="password" id="password" placeholder="Password">',
                '        <br>',
                '        <button onclick="login()">Login</button>',
                '        <p id="loginMessage"></p>',
                '    </div>',
                '    <div id="todoBox" class="hidden">',
                '        <h1>My TO-DO List</h1>',
                '        <button onclick="logout()">Logout</button>',
                '        <br><br>',
                '        <input type="text" id="taskInput" placeholder="Enter a task">',
                '        <button onclick="addTask()">Add</button>',
                '        <ul id="taskList"></ul>',
                '    </div>',
                '</div>',
                '<script src="index.js"></script>',
                '</body>',
                '</html>',
            ]),
            ("INDEX.JS :", [
                'let tasks = [];',
                'function login() {',
                '    const username = document.getElementById("username").value;',
                '    const password = document.getElementById("password").value;',
                '    if (username === "admin" && password === "1234") {',
                '        document.getElementById("loginBox").classList.add("hidden");',
                '        document.getElementById("todoBox").classList.remove("hidden");',
                '        loadTasks();',
                '    } else {',
                '        document.getElementById("loginMessage").innerText = "Invalid username or password";',
                '    }',
                '}',
                'function logout() {',
                '    document.getElementById("todoBox").classList.add("hidden");',
                '    document.getElementById("loginBox").classList.remove("hidden");',
                '}',
                'function addTask() {',
                '    const input = document.getElementById("taskInput");',
                '    const task = input.value.trim();',
                '    if (task === "") { alert("Please enter a task"); return; }',
                '    tasks.push({ id: Date.now(), title: task, completed: false });',
                '    input.value = "";',
                '    loadTasks();',
                '}',
                'function loadTasks() {',
                '    const list = document.getElementById("taskList");',
                '    list.innerHTML = "";',
                '    tasks.forEach(task => {',
                '        const li = document.createElement("li");',
                '        if (task.completed) { li.classList.add("completed"); }',
                '        li.innerHTML = `<span>${task.title}</span>` +',
                '            `<div>` +',
                '                `<button onclick="completeTask(${task.id})">✓</button>` +',
                '                `<button onclick="editTask(${task.id})">Edit</button>` +',
                '                `<button onclick="deleteTask(${task.id})">Delete</button>` +',
                '            `</div>`;',
                '        list.appendChild(li);',
                '    });',
                '}',
                'function completeTask(id) {',
                '    const task = tasks.find(task => task.id === id);',
                '    if (task) { task.completed = !task.completed; }',
                '    loadTasks();',
                '}',
                'function deleteTask(id) {',
                '    tasks = tasks.filter(task => task.id !== id);',
                '    loadTasks();',
                '}',
            ]),
            ("SERVER.JS :", [
                'const express = require("express");',
                'const path = require("path");',
                'const app = express();',
                'const PORT = 3000;',
                'app.use(express.json());',
                'app.use(express.static(__dirname));',
                'app.get("/", (req, res) => {',
                '    res.sendFile(path.join(__dirname, "index.html"));',
                '});',
                'app.listen(PORT, () => {',
                '    console.log(`Server running at http://localhost:${PORT}`);',
                '});',
            ]),
        ],
    },
    {
        "num": 3,
        "title": "CREATE A SIMPLE MICRO BLOGGING APPLICATION THAT ALLOWS PEOPLE TO POST THEIR CONTENT",
        "desc": "WHICH CAN BE VIEWED BY PEOPLE WHO FOLLOW THEM",
        "marks": "9665",
        "files": [
            ("INDEX.HTML :", [
                '<!DOCTYPE html>',
                '<html>',
                '<head>',
                '    <title>Micro Blog</title>',
                '</head>',
                '<body>',
                '<nav><h1>Micro Blog</h1></nav>',
                '<div class="container">',
                '    <div class="box" id="loginBox">',
                '        <h2>Login</h2>',
                '        <input type="text" id="username" placeholder="Enter username">',
                '        <button onclick="login()">Login</button>',
                '        <p id="loginMessage"></p>',
                '    </div>',
                '    <div class="box" id="postBox" style="display:none;">',
                '        <h2>Create Post</h2>',
                '        <textarea id="postContent" placeholder="What\'s happening?"></textarea>',
                '        <button onclick="createPost()">Publish</button>',
                '    </div>',
                '    <div class="box" id="followBox" style="display:none;">',
                '        <h2>Users</h2>',
                '        <div id="users"></div>',
                '    </div>',
                '    <div class="box" id="feedBox" style="display:none;">',
                '        <h2>My Feed</h2>',
                '        <div id="feed"></div>',
                '    </div>',
                '</div>',
                '<script src="index.js"></script>',
                '</body>',
                '</html>',
            ]),
            ("INDEX.JS :", [
                'let currentUser = "";',
                'let users = [',
                '    { username: "hari", following: [] },',
                '    { username: "arun", following: [] },',
                '    { username: "kumar", following: [] },',
                '    { username: "priya", following: [] },',
                '];',
                'let posts = [];',
                'function login() {',
                '    const username = document.getElementById("username").value.trim();',
                '    if (username === "") { alert("Enter username"); return; }',
                '    currentUser = username;',
                '    document.getElementById("postBox").style.display = "block";',
                '    document.getElementById("followBox").style.display = "block";',
                '    document.getElementById("feedBox").style.display = "block";',
                '    showUsers(); showFeed();',
                '}',
                'function createPost() {',
                '    const content = document.getElementById("postContent").value.trim();',
                '    if (content === "") { alert("Write something first"); return; }',
                '    posts.push({ username: currentUser, content: content, date: new Date().toLocaleString() });',
                '    document.getElementById("postContent").value = "";',
                '    showFeed();',
                '}',
                'function showUsers() {',
                '    const usersDiv = document.getElementById("users");',
                '    usersDiv.innerHTML = "";',
                '    users.forEach(user => {',
                '        if (user.username === currentUser) return;',
                '        const current = users.find(u => u.username === currentUser);',
                '        const following = current.following.includes(user.username);',
                '        usersDiv.innerHTML += `<div style="margin:10px 0;">` +',
                '            `<b>@${user.username}</b>` +',
                '            `<button onclick="followUser(\'${user.username}\')">` +',
                '                `${following ? "Unfollow" : "Follow"}` +',
                '            `</button></div>`;',
                '    });',
                '}',
                'function followUser(username) {',
                '    const current = users.find(u => u.username === currentUser);',
                '    if (current.following.includes(username)) {',
                '        current.following = current.following.filter(n => n !== username);',
                '    } else { current.following.push(username); }',
                '    showUsers(); showFeed();',
                '}',
                'function showFeed() {',
                '    const feed = document.getElementById("feed");',
                '    feed.innerHTML = "";',
                '    const current = users.find(u => u.username === currentUser);',
                '    const feedPosts = posts.filter(post =>',
                '        post.username === currentUser || current.following.includes(post.username)',
                '    );',
                '    feedPosts.reverse().forEach(post => {',
                '        feed.innerHTML += `<div class="post">` +',
                '            `<div class="username">@${post.username}</div>` +',
                '            `<p>${post.content}</p>` +',
                '            `<small>${post.date}</small>` +',
                '        `</div>`;',
                '    });',
                '}',
            ]),
        ],
    },
    {
        "num": 4,
        "title": "CREATE A FOOD DELIVERY WEBSITE WHERE USERS CAN ORDER FOOD FROM A PARTICULAR RESTAURANT LISTED IN THE WEBSITE",
        "desc": "",
        "marks": "9665",
        "files": [
            ("INDEX.HTML :", [
                '<!DOCTYPE html>',
                '<html>',
                '<head>',
                '    <title>Food Delivery</title>',
                '</head>',
                '<body>',
                '<header><h1>Food Delivery</h1><p>Order your favorite food</p></header>',
                '<div class="container">',
                '    <h2>Food Menu</h2>',
                '    <div class="foods">',
                '        <div class="food"><h3>Pizza</h3><p>Cheese Pizza</p><h4>₹199</h4>',
                '            <button onclick="addToCart(\'Pizza\', 199)">Add to Cart</button></div>',
                '        <div class="food"><h3>Burger</h3><p>Chicken Burger</p><h4>₹149</h4>',
                '            <button onclick="addToCart(\'Burger\', 149)">Add to Cart</button></div>',
                '        <div class="food"><h3>French Fries</h3><p>Crispy Fries</p><h4>₹99</h4>',
                '            <button onclick="addToCart(\'Fries\', 99)">Add to Cart</button></div>',
                '        <div class="food"><h3>Pasta</h3><p>White Sauce Pasta</p><h4>₹179</h4>',
                '            <button onclick="addToCart(\'Pasta\', 179)">Add to Cart</button></div>',
                '        <div class="food"><h3>Coke</h3><p>Chilled Coke</p><h4>₹49</h4>',
                '            <button onclick="addToCart(\'Coke\', 49)">Add to Cart</button></div>',
                '        <div class="food"><h3>Ice Cream</h3><p>Chocolate Ice Cream</p><h4>₹89</h4>',
                '            <button onclick="addToCart(\'IceCream\', 89)">Add to Cart</button></div>',
                '    </div>',
                '    <div class="cart">',
                '        <h2>My Cart</h2>',
                '        <div id="cartItems"><p>Your cart is empty.</p></div>',
                '        <div class="total">Total: ₹<span id="total">0</span></div>',
                '        <br><button onclick="placeOrder()">Place Order</button>',
                '    </div>',
                '</div>',
                '<script src="index.js"></script>',
                '</body>',
                '</html>',
            ]),
            ("INDEX.JS :", [
                'let cart = [];',
                'function addToCart(name, price) {',
                '    let item = cart.find(food => food.name === name);',
                '    if (item) { item.quantity++; }',
                '    else { cart.push({ name: name, price: price, quantity: 1 }); }',
                '    displayCart();',
                '}',
                'function displayCart() {',
                '    const cartItems = document.getElementById("cartItems");',
                '    const totalElement = document.getElementById("total");',
                '    cartItems.innerHTML = "";',
                '    let total = 0;',
                '    if (cart.length === 0) {',
                '        cartItems.innerHTML = "<p>Your cart is empty.</p>";',
                '        totalElement.innerText = "0"; return;',
                '    }',
                '    cart.forEach((item, index) => {',
                '        let itemTotal = item.price * item.quantity;',
                '        total += itemTotal;',
                '        cartItems.innerHTML += `<div class="cart-item">` +',
                '            `<b>${item.name}</b>` +',
                '            `<p>₹${item.price} x ${item.quantity} = ₹${itemTotal}</p>` +',
                '            `<button onclick="increase(${index})">+</button>` +',
                '            `<button onclick="decrease(${index})">-</button>` +',
                '            `<button onclick="removeItem(${index})">Remove</button>` +',
                '        `</div>`;',
                '    });',
                '    totalElement.innerText = total;',
                '}',
                'function increase(index) { cart[index].quantity++; displayCart(); }',
                'function decrease(index) {',
                '    cart[index].quantity--;',
                '    if (cart[index].quantity <= 0) { cart.splice(index, 1); }',
                '    displayCart();',
                '}',
                'function removeItem(index) { cart.splice(index, 1); displayCart(); }',
                'function placeOrder() {',
                '    if (cart.length === 0) { alert("Your cart is empty!"); return; }',
                '    let total = 0;',
                '    cart.forEach(item => { total += item.price * item.quantity; });',
                '    alert("Order placed successfully!\\nTotal Amount: ₹" + total);',
                '    cart = []; displayCart();',
                '}',
            ]),
            ("SERVER.JS :", [
                'const express = require("express");',
                'const path = require("path");',
                'const app = express();',
                'const PORT = 3000;',
                'app.use(express.json());',
                'app.use(express.static(__dirname));',
                'app.get("/", (req, res) => {',
                '    res.sendFile(path.join(__dirname, "index.html"));',
                '});',
                'app.listen(PORT, () => {',
                '    console.log(`Server running at http://localhost:${PORT}`);',
                '});',
            ]),
        ],
    },
    {
        "num": 5,
        "title": "DEVELOP A CLASSIFIEDS WEB APPLICATION TO BUY AND SELL USED PRODUCTS",
        "desc": "",
        "marks": "9665",
        "files": [
            ("INDEX.HTML :", [
                '<!DOCTYPE html>',
                '<html lang="en">',
                '<head>',
                '    <meta charset="UTF-8" />',
                '    <title>Classifieds</title>',
                '</head>',
                '<body>',
                '<header><h1>Classifieds</h1></header>',
                '<div class="container">',
                '    <div class="add-product">',
                '        <h2>Add Product</h2>',
                '        <input type="text" id="name" placeholder="Product name">',
                '        <input type="number" id="price" placeholder="Price">',
                '        <input type="text" id="seller" placeholder="Seller name">',
                '        <textarea id="description" placeholder="Description"></textarea>',
                '        <button onclick="addProduct()">Add Product</button>',
                '    </div>',
                '    <div class="products">',
                '        <h2>Available Products</h2>',
                '        <div id="products"></div>',
                '    </div>',
                '</div>',
                '<script src="index.js"></script>',
                '</body>',
                '</html>',
            ]),
            ("INDEX.JS :", [
                'let products = [',
                '    { id: 1, name: "iPhone 13", price: 35000, seller: "Arun", description: "Good condition" },',
                '    { id: 2, name: "HP Laptop", price: 25000, seller: "Kumar", description: "8GB RAM, 512GB SSD" },',
                '];',
                'function displayProducts() {',
                '    const productList = document.getElementById("products");',
                '    productList.innerHTML = "";',
                '    products.forEach(product => {',
                '        productList.innerHTML += `<div class="product">` +',
                '            `<h3>${product.name}</h3>` +',
                '            `<p class="price">₹${product.price}</p>` +',
                '            `<p>${product.description}</p>` +',
                '            `<p><b>Seller:</b> ${product.seller}</p>` +',
                '            `<button onclick="buyProduct(${product.id})">Contact Seller</button>` +',
                '            `<button class="delete" onclick="deleteProduct(${product.id})">Delete</button>` +',
                '        `</div>`;',
                '    });',
                '}',
                'function addProduct() {',
                '    let name = document.getElementById("name").value;',
                '    let price = document.getElementById("price").value;',
                '    let seller = document.getElementById("seller").value;',
                '    let desc = document.getElementById("description").value;',
                '    if (name === "" || price === "" || seller === "") { alert("Fill all fields"); return; }',
                '    let product = { id: Date.now(), name, price, seller, description: desc };',
                '    products.push(product);',
                '    document.getElementById("name").value = "";',
                '    document.getElementById("price").value = "";',
                '    document.getElementById("seller").value = "";',
                '    document.getElementById("description").value = "";',
                '    displayProducts();',
                '}',
                'function buyProduct(id) {',
                '    let product = products.find(p => p.id === id);',
                '    alert("Seller: " + product.seller + "\\nProduct: " + product.name + "\\nPrice: ₹" + product.price);',
                '}',
                'function deleteProduct(id) {',
                '    products = products.filter(product => product.id !== id);',
                '    displayProducts();',
                '}',
                'displayProducts();',
            ]),
            ("SERVER.JS :", [
                'const express = require("express");',
                'const path = require("path");',
                'const app = express();',
                'const PORT = 3000;',
                'app.use(express.json());',
                'app.use(express.static(__dirname));',
                'app.get("/", (req, res) => {',
                '    res.sendFile(path.join(__dirname, "index.html"));',
                '});',
                'app.listen(PORT, () => {',
                '    console.log(`Server running at http://localhost:${PORT}`);',
                '});',
            ]),
        ],
    },
    {
        "num": 6,
        "title": "DEVELOP A LEAVE MANAGEMENT SYSTEM TO MANAGE EMPLOYEE LEAVE REQUESTS",
        "desc": "",
        "marks": "9665",
        "files": [
            ("INDEX.HTML :", [
                '<!DOCTYPE html>',
                '<html>',
                '<head>',
                '    <title>Leave Management</title>',
                '</head>',
                '<body>',
                '<header><h1>Leave Management</h1></header>',
                '<div class="container">',
                '    <div class="balance-card">',
                '        <h2>Leave Balance</h2>',
                '        <p>Sick Leave: <span id="sick">5</span> days</p>',
                '        <p>Casual Leave: <span id="casual">5</span> days</p>',
                '        <p>Annual Leave: <span id="annual">10</span> days</p>',
                '    </div>',
                '    <div class="apply-leave">',
                '        <h2>Apply for Leave</h2>',
                '        <select id="leaveType">',
                '            <option value="Sick">Sick Leave</option>',
                '            <option value="Casual">Casual Leave</option>',
                '            <option value="Annual">Annual Leave</option>',
                '        </select>',
                '        <input type="date" id="fromDate">',
                '        <input type="date" id="toDate">',
                '        <textarea id="reason" placeholder="Reason"></textarea>',
                '        <button onclick="applyLeave()">Apply</button>',
                '        <p id="applyMessage"></p>',
                '    </div>',
                '    <div class="requests">',
                '        <h2>My Requests</h2>',
                '        <div id="requestList"></div>',
                '    </div>',
                '</div>',
                '<script src="index.js"></script>',
                '</body>',
                '</html>',
            ]),
            ("INDEX.JS :", [
                'let requests = [',
                '    { id: 1, type: "Sick", from: "2024-01-10", to: "2024-01-12", status: "approved" },',
                '];',
                'function applyLeave() {',
                '    const type = document.getElementById("leaveType").value;',
                '    const from = document.getElementById("fromDate").value;',
                '    const to = document.getElementById("toDate").value;',
                '    const reason = document.getElementById("reason").value;',
                '    if (!from || !to) { alert("Please select dates"); return; }',
                '    const req = { id: Date.now(), type, from, to, status: "pending" };',
                '    requests.push(req);',
                '    showRequests();',
                '    document.getElementById("applyMessage").innerText = "Request submitted";',
                '}',
                'function showRequests() {',
                '    const list = document.getElementById("requestList");',
                '    list.innerHTML = "";',
                '    requests.forEach(req => {',
                '        list.innerHTML += `<div class="request">` +',
                '            `<p><b>${req.type}</b>: ${req.from} to ${req.to}</p>` +',
                '            `<span class="status">${req.status}</span>` +',
                '        `</div>`;',
                '    });',
                '}',
                'function cancelRequest(id) {',
                '    requests = requests.filter(r => r.id !== id);',
                '    showRequests();',
                '}',
                'showRequests();',
            ]),
            ("SERVER.JS :", [
                'const express = require("express");',
                'const path = require("path");',
                'const app = express();',
                'const PORT = 3000;',
                'app.use(express.json());',
                'app.use(express.static(__dirname));',
                'app.get("/", (req, res) => {',
                '    res.sendFile(path.join(__dirname, "index.html"));',
                '});',
                'app.listen(PORT, () => {',
                '    console.log(`Server running at http://localhost:${PORT}`);',
                '});',
            ]),
        ],
    },
    {
        "num": 7,
        "title": "DEVELOP A PROJECT MANAGEMENT TOOL FOR TRACKING TASKS AND PROJECTS",
        "desc": "",
        "marks": "9665",
        "files": [
            ("INDEX.HTML :", [
                '<!DOCTYPE html>',
                '<html>',
                '<head>',
                '    <title>Project Management</title>',
                '</head>',
                '<body>',
                '<header><h1>Project Management</h1></header>',
                '<div class="container">',
                '    <div class="sidebar">',
                '        <h2>Projects</h2>',
                '        <div id="projectList"></div>',
                '        <button onclick="showAddProject()">Add Project</button>',
                '    </div>',
                '    <div class="main">',
                '        <div id="projectView">',
                '            <h2 id="projTitle"></h2>',
                '            <div id="taskList"></div>',
                '            <button onclick="showAddTask()">Add Task</button>',
                '        </div>',
                '    </div>',
                '</div>',
                '<script src="index.js"></script>',
                '</body>',
                '</html>',
            ]),
            ("INDEX.JS :", [
                'let projects = [',
                '    { id: 1, name: "Web App", tasks: [] },',
                '    { id: 2, name: "Mobile App", tasks: [] },',
                '];',
                'function loadProjects() {',
                '    const list = document.getElementById("projectList");',
                '    list.innerHTML = "";',
                '    projects.forEach(p => {',
                '        list.innerHTML += `<div class="project-item">` +',
                '            `<h3 onclick="openProject(${p.id})">${p.name}</h3>` +',
                '            `<small>${p.tasks.length} tasks</small>` +',
                '        `</div>`;',
                '    });',
                '}',
                'function openProject(id) {',
                '    const proj = projects.find(p => p.id === id);',
                '    document.getElementById("projTitle").innerText = proj.name;',
                '    const taskList = document.getElementById("taskList");',
                '    taskList.innerHTML = "";',
                '    proj.tasks.forEach(task => {',
                '        taskList.innerHTML += `<div class="task">` +',
                '            `<span class="${task.done ? "done" : ""}">${task.title}</span>` +',
                '            `<button onclick="toggleTask(${proj.id}, ${task.id})">✓</button>` +',
                '            `<button onclick="deleteTask(${proj.id}, ${task.id})">Delete</button>` +',
                '        `</div>`;',
                '    });',
                '}',
                'function showAddTask() {',
                '    const title = prompt("Enter task title:");',
                '    if (!title) return;',
                '    const activeProj = projects.find(p => p.tasks.length > 0) || projects[0];',
                '    activeProj.tasks.push({ id: Date.now(), title, done: false });',
                '    openProject(activeProj.id);',
                '}',
                'function toggleTask(projId, taskId) {',
                '    const proj = projects.find(p => p.id === projId);',
                '    const task = proj.tasks.find(t => t.id === taskId);',
                '    if (task) task.done = !task.done;',
                '    openProject(projId);',
                '}',
                'function deleteTask(projId, taskId) {',
                '    const proj = projects.find(p => p.id === projId);',
                '    proj.tasks = proj.tasks.filter(t => t.id !== taskId);',
                '    openProject(projId);',
                '}',
                'loadProjects();',
            ]),
            ("SERVER.JS :", [
                'const express = require("express");',
                'const path = require("path");',
                'const app = express();',
                'const PORT = 3000;',
                'app.use(express.json());',
                'app.use(express.static(__dirname));',
                'app.get("/", (req, res) => {',
                '    res.sendFile(path.join(__dirname, "index.html"));',
                '});',
                'app.listen(PORT, () => {',
                '    console.log(`Server running at http://localhost:${PORT}`);',
                '});',
            ]),
        ],
    },
    {
        "num": 8,
        "title": "DEVELOP AN ONLINE SURVEY SYSTEM TO CREATE AND MANAGE SURVEYS",
        "desc": "",
        "marks": "9665",
        "files": [
            ("INDEX.HTML :", [
                '<!DOCTYPE html>',
                '<html>',
                '<head>',
                '    <title>Online Survey</title>',
                '</head>',
                '<body>',
                '<header><h1>Online Survey</h1></header>',
                '<div class="container">',
                '    <div id="surveyStart">',
                '        <h2>Select a Survey</h2>',
                '        <button onclick="startSurvey()">Start Survey</button>',
                '    </div>',
                '    <div id="surveyForm" style="display:none;">',
                '        <h2 id="questionText"></h2>',
                '        <div id="options"></div>',
                '        <button onclick="nextQuestion()">Next</button>',
                '    </div>',
                '    <div id="result" style="display:none;">',
                '        <h2>Survey Completed</h2>',
                '        <p id="scoreText"></p>',
                '    </div>',
                '</div>',
                '<script src="index.js"></script>',
                '</body>',
                '</html>',
            ]),
            ("INDEX.JS :", [
                'let questions = [',
                '    { id: 1, text: "What is your favorite language?", type: "MCQ",',
                '      options: ["HTML", "CSS", "JavaScript", "Python"], correct: 2 },',
                '    { id: 2, text: "Is JavaScript object-oriented?", type: "TF",',
                '      options: ["True", "False"], correct: 0 },',
                '    { id: 3, text: "Name a frontend framework", type: "SA", correct: "" },',
                '];',
                'let currentQ = 0;',
                'let score = 0;',
                'function startSurvey() {',
                '    document.getElementById("surveyStart").style.display = "none";',
                '    document.getElementById("surveyForm").style.display = "block";',
                '    showQuestion();',
                '}',
                'function showQuestion() {',
                '    const q = questions[currentQ];',
                '    document.getElementById("questionText").innerText = q.text;',
                '    const optDiv = document.getElementById("options");',
                '    optDiv.innerHTML = "";',
                '    q.options.forEach((opt, i) => {',
                '        optDiv.innerHTML += `<label><input type="${q.type === "TF" ? "radio" : "radio"} name="ans" value="${i}"> ${opt}</label>`;',
                '    });',
                '}',
                'function nextQuestion() {',
                '    const selected = document.querySelector(\'input[name="ans"]:checked\');',
                '    if (!selected) { alert("Select an option"); return; }',
                '    const q = questions[currentQ];',
                '    if (parseInt(selected.value) === q.correct) { score++; }',
                '    currentQ++;',
                '    if (currentQ >= questions.length) { showResult(); }',
                '    else { showQuestion(); }',
                '}',
                'function showResult() {',
                '    document.getElementById("surveyForm").style.display = "none";',
                '    document.getElementById("result").style.display = "block";',
                '    document.getElementById("scoreText").innerText = "Score: " + score + "/" + questions.length;',
                '}',
            ]),
            ("SERVER.JS :", [
                'const express = require("express");',
                'const path = require("path");',
                'const app = express();',
                'const PORT = 3000;',
                'app.use(express.json());',
                'app.use(express.static(__dirname));',
                'app.get("/", (req, res) => {',
                '    res.sendFile(path.join(__dirname, "index.html"));',
                '});',
                'app.listen(PORT, () => {',
                '    console.log(`Server running at http://localhost:${PORT}`);',
                '});',
            ]),
        ],
    },
]


def add_output_space(doc):
    p = doc.add_paragraph()
    r = p.add_run("OUTPUT :")
    r.bold = True
    r.font.size = Pt(14)
    r.font.name = "Cambria"
    for _ in range(90):
        doc.add_paragraph("")


doc = Document()

style = doc.styles["Normal"]
style.font.name = "Cambria"
style.font.size = Pt(12)

# Title page
for _ in range(4):
    doc.add_paragraph("")

t = doc.add_paragraph(); t.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = t.add_run("Full Stack Web Lab — Experiments 2 to 8"); r.bold = True; r.font.size = Pt(20); r.font.name = "Cambria"

s = doc.add_paragraph(); s.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = s.add_run("HTML Structure | CSS Styles | JavaScript | Server Code"); r.font.size = Pt(14); r.font.name = "Cambria"

info = doc.add_paragraph(); info.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = info.add_run("Flutter Web + FastAPI + MongoDB\nSimplified web equivalents for reference"); r.font.size = Pt(12); r.font.name = "Cambria"

doc.add_page_break()

for exp in EXPS:
    # EX.NO heading
    h = doc.add_paragraph()
    r = h.add_run(f"EX.NO: {exp['num']}    {exp['title']}    {exp['marks']}")
    r.bold = True
    r.font.size = Pt(14)
    r.font.name = "Cambria"

    if exp['desc']:
        p = doc.add_paragraph()
        r = p.add_run(f"                         {exp['desc']}")
        r.font.size = Pt(12)
        r.font.name = "Cambria"

    doc.add_paragraph("")

    # PROGRAM section
    p = doc.add_paragraph()
    r = p.add_run("PROGRAM :"); r.bold = True; r.font.size = Pt(14); r.font.name = "Cambria"
    doc.add_paragraph("")

    # Code files
    for label, lines in exp['files']:
        add_code_block(doc, label, lines, font_size=12)
        for _ in range(8):
            doc.add_paragraph("")

    # OUTPUT space
    add_output_space(doc)

    # RESULT section
    p = doc.add_paragraph()
    r = p.add_run("RESULT :"); r.bold = True; r.font.size = Pt(14); r.font.name = "Cambria"
    doc.add_paragraph("")

    doc.add_page_break()

filepath = OUT / "All_Experiments_2_to_8_Code_Snippets.docx"
doc.save(str(filepath))
print(f"✅ Generated: {filepath.name}")
