#!/usr/bin/env python3
from pathlib import Path
from docx import Document
from docx.shared import Pt

BASE = Path("/home/mani-arch/Desktop/FSD lab/fullstack-web-lab")
OUT = BASE / "documents"
OUT.mkdir(exist_ok=True)

EXPS = [
    (2, "todo", "TODO APPLICATION", "Manage the To-Do list of users where users can login and manage their To-Do items"),
    (3, "microblog", "MICRO BLOGGING APPLICATION", "Allows people to post their content which can be viewed by people who follow them"),
    (4, "fooddelivery", "FOOD DELIVERY WEBSITE", "Users can order food from a particular restaurant listed in the website"),
    (5, "classifieds", "CLASSIFIEDS WEB APPLICATION", "Buy and sell used products"),
    (6, "leave", "LEAVE MANAGEMENT SYSTEM", "Manage employee leave requests"),
    (7, "project", "PROJECT MANAGEMENT TOOL", "Tracking tasks and projects"),
    (8, "survey", "ONLINE SURVEY SYSTEM", "Create and manage surveys"),
]

# Single consolidated code per experiment - frontend / CSS / server
CODE = {
 2: {
  "frontend": [
    '<!DOCTYPE html>',
    '<html><head><title>TO-DO List</title>',
    '<link rel="stylesheet" href="todo.css"></head><body>',
    '<div class="container">',
    '  <div id="loginBox">',
    '    <h1>TO-DO List</h1><h2>Login</h2>',
    '    <input type="text" id="username" placeholder="Username">',
    '    <input type="password" id="password" placeholder="Password">',
    '    <button onclick="login()">Login</button>',
    '    <p id="loginMessage"></p>',
    '  </div>',
    '  <div id="todoBox" class="hidden">',
    '    <h1>My TO-DO List</h1>',
    '    <button onclick="logout()">Logout</button>',
    '    <input type="text" id="taskInput" placeholder="Enter a task">',
    '    <button onclick="addTask()">Add</button>',
    '    <ul id="taskList"></ul>',
    '  </div>',
    '</div>',
    '<script src="todo.frontend.js"></script>',
    '</body></html>',
    '',
    'let tasks = [];',
    'function login(){',
    '  const u=document.getElementById("username").value;',
    '  const p=document.getElementById("password").value;',
    '  if(u==="admin"&&p==="1234"){',
    '    document.getElementById("loginBox").classList.add("hidden");',
    '    document.getElementById("todoBox").classList.remove("hidden");',
    '    loadTasks();',
    '  } else { document.getElementById("loginMessage").innerText="Invalid username or password"; }',
    '}',
    'function addTask(){',
    '  const input=document.getElementById("taskInput");',
    '  const task=input.value.trim();',
    '  if(task===""){ alert("Please enter a task"); return; }',
    '  tasks.push({id:Date.now(), title:task, completed:false});',
    '  input.value=""; loadTasks();',
    '}',
    'function loadTasks(){',
    '  const list=document.getElementById("taskList"); list.innerHTML="";',
    '  tasks.forEach(task=>{',
    '    const li=document.createElement("li");',
    '    if(task.completed) li.classList.add("completed");',
    '    li.innerHTML=`<span>${task.title}</span><div><button onclick="completeTask(${task.id})">Done</button><button onclick="deleteTask(${task.id})">Delete</button></div>`;',
    '    list.appendChild(li);',
    '  });',
    '}',
    'function completeTask(id){ const t=tasks.find(x=>x.id===id); if(t) t.completed=!t.completed; loadTasks(); }',
    'function deleteTask(id){ tasks=tasks.filter(x=>x.id!==id); loadTasks(); }',
  ],
  "css": [
    'body{margin:0;font-family:Cambria;background:#f4f4f4;color:#222;}',
    '.container{max-width:700px;margin:0 auto;padding:20px;}',
    'h1{text-align:center;color:#222;}',
    'input{padding:10px;margin:6px;border:1px solid #ccc;border-radius:6px;width:200px;}',
    'button{padding:10px 18px;background:#222;color:#fff;border:none;border-radius:6px;cursor:pointer;}',
    'button:hover{background:#00bcd4;}',
    '.hidden{display:none;}',
    '#taskList{list-style:none;padding:0;}',
    '#taskList li{display:flex;justify-content:space-between;padding:10px;margin:6px 0;background:#fff;border-radius:6px;}',
    '.completed{opacity:0.6;text-decoration:line-through;}',
  ],
  "server": [
    'const express=require("express");',
    'const path=require("path");',
    'const app=express();',
    'const PORT=3000;',
    'app.use(express.json());',
    'app.use(express.static(__dirname));',
    'let todos=[];',
    'app.get("/api/todos",(req,res)=>{ res.json({success:true,data:todos}); });',
    'app.post("/api/todos",(req,res)=>{',
    '  const todo={id:Date.now(),title:req.body.title,completed:false};',
    '  todos.push(todo); res.json({success:true,data:todo});',
    '});',
    'app.put("/api/todos/:id",(req,res)=>{',
    '  const t=todos.find(x=>x.id==req.params.id);',
    '  if(t) Object.assign(t,req.body);',
    '  res.json({success:true,data:t});',
    '});',
    'app.delete("/api/todos/:id",(req,res)=>{',
    '  todos=todos.filter(x=>x.id!=req.params.id);',
    '  res.json({success:true,message:"Deleted"});',
    '});',
    'app.get("/",(req,res)=>res.sendFile(path.join(__dirname,"todo.frontend.html")));',
    'app.listen(PORT,()=>console.log(`Server running at http://localhost:${PORT}`));',
  ],
 },
 3: {
  "frontend": [
    '<!DOCTYPE html><html><head><title>Micro Blog</title>',
    '<link rel="stylesheet" href="microblog.css"></head><body>',
    '<nav><h1>Micro Blog</h1></nav>',
    '<div class="container">',
    '  <div class="box"><h2>Login</h2>',
    '    <input type="text" id="username" placeholder="Enter username">',
    '    <button onclick="login()">Login</button><p id="loginMessage"></p>',
    '  </div>',
    '  <div class="box" id="postBox" style="display:none;">',
    '    <textarea id="postContent" placeholder="What\'s happening?"></textarea>',
    '    <button onclick="createPost()">Publish</button>',
    '  </div>',
    '  <div class="box" id="followBox" style="display:none;"><h2>Users</h2><div id="users"></div></div>',
    '  <div class="box" id="feedBox" style="display:none;"><h2>My Feed</h2><div id="feed"></div></div>',
    '</div>',
    '<script src="microblog.frontend.js"></script>',
    '</body></html>',
    '',
    'let currentUser=""; let users=[{username:"hari",following:[]},{username:"arun",following:[]}]; let posts=[];',
    'function login(){',
    '  const u=document.getElementById("username").value.trim();',
    '  if(!u){alert("Enter username");return;}',
    '  currentUser=u;',
    '  document.getElementById("postBox").style.display="block";',
    '  document.getElementById("followBox").style.display="block";',
    '  document.getElementById("feedBox").style.display="block";',
    '  showUsers(); showFeed();',
    '}',
    'function createPost(){',
    '  const c=document.getElementById("postContent").value.trim();',
    '  if(!c){alert("Write something");return;}',
    '  posts.push({username:currentUser,content:c,date:new Date().toLocaleString()});',
    '  document.getElementById("postContent").value=""; showFeed();',
    '}',
    'function showFeed(){',
    '  const feed=document.getElementById("feed"); feed.innerHTML="";',
    '  const cur=users.find(x=>x.username===currentUser);',
    '  posts.filter(p=>p.username===currentUser||cur.following.includes(p.username)).reverse().forEach(p=>{',
    '    feed.innerHTML+=`<div class="post"><b>@${p.username}</b><p>${p.content}</p><small>${p.date}</small></div>`;',
    '  });',
    '}',
  ],
  "css": [
    'body{margin:0;font-family:Cambria;background:#f4f4f4;}',
    'nav{background:#222;color:#fff;padding:16px;text-align:center;}',
    '.container{max-width:700px;margin:0 auto;padding:20px;}',
    '.box{background:#fff;padding:16px;margin:12px 0;border-radius:8px;box-shadow:0 2px 6px rgba(0,0,0,0.1);}',
    'textarea{width:100%;height:80px;padding:10px;border:1px solid #ccc;border-radius:6px;}',
    'input{padding:10px;border:1px solid #ccc;border-radius:6px;}',
    'button{padding:8px 16px;background:#222;color:#fff;border:none;border-radius:6px;cursor:pointer;}',
    '.post{padding:12px;border-bottom:1px solid #eee;}',
  ],
  "server": [
    'const express=require("express"); const app=express(); app.use(express.json());',
    'let posts=[]; let users=[{username:"hari",following:[]}];',
    'app.get("/api/posts/feed",(req,res)=>{ res.json({success:true,data:posts}); });',
    'app.post("/api/posts",(req,res)=>{',
    '  const p={id:Date.now(),username:req.body.username,content:req.body.content,date:new Date().toLocaleString()};',
    '  posts.push(p); res.json({success:true,data:p});',
    '});',
    'app.post("/api/follows/:id",(req,res)=>{',
    '  const u=users.find(x=>x.username===req.params.id);',
    '  if(u) u.following.push(req.body.follower);',
    '  res.json({success:true});',
    '});',
    'app.listen(3000,()=>console.log("Micro Blog running"));',
  ],
 },
 4: {
  "frontend": [
    '<!DOCTYPE html><html><head><title>Food Delivery</title>',
    '<link rel="stylesheet" href="fooddelivery.css"></head><body>',
    '<header><h1>Food Delivery</h1><p>Order your favorite food</p></header>',
    '<div class="container"><h2>Food Menu</h2><div class="foods">',
    '  <div class="food"><h3>Pizza</h3><p>Cheese Pizza</p><h4>Rs.199</h4><button onclick="addToCart(\'Pizza\',199)">Add to Cart</button></div>',
    '  <div class="food"><h3>Burger</h3><p>Chicken Burger</p><h4>Rs.149</h4><button onclick="addToCart(\'Burger\',149)">Add to Cart</button></div>',
    '  <div class="food"><h3>Fries</h3><p>Crispy Fries</p><h4>Rs.99</h4><button onclick="addToCart(\'Fries\',99)">Add to Cart</button></div>',
    '</div>',
    '<div class="cart"><h2>My Cart</h2><div id="cartItems"><p>Your cart is empty.</p></div>',
    '  <div>Total: Rs.<span id="total">0</span></div><button onclick="placeOrder()">Place Order</button></div></div>',
    '<script src="fooddelivery.frontend.js"></script></body></html>',
    '',
    'let cart=[];',
    'function addToCart(name,price){',
    '  let item=cart.find(x=>x.name===name);',
    '  if(item) item.quantity++; else cart.push({name,price,quantity:1});',
    '  displayCart();',
    '}',
    'function displayCart(){',
    '  let total=0; const div=document.getElementById("cartItems"); div.innerHTML="";',
    '  cart.forEach((item,i)=>{',
    '    total+=item.price*item.quantity;',
    '    div.innerHTML+=`<div class="cart-item"><b>${item.name}</b> Rs.${item.price} x ${item.quantity} <button onclick="increase(${i})">+</button><button onclick="decrease(${i})">-</button></div>`;',
    '  });',
    '  document.getElementById("total").innerText=total;',
    '}',
    'function placeOrder(){ if(!cart.length){alert("Cart empty");return;} alert("Order placed! Total Rs."+document.getElementById("total").innerText); cart=[]; displayCart(); }',
  ],
  "css": [
    'body{margin:0;font-family:Cambria;background:#f4f4f4;}',
    'header{background:#222;color:#fff;padding:20px;text-align:center;}',
    '.container{max-width:900px;margin:0 auto;padding:20px;}',
    '.foods{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;}',
    '.food{background:#fff;padding:16px;border-radius:8px;text-align:center;box-shadow:0 2px 6px rgba(0,0,0,0.1);}',
    '.cart{background:#fff;padding:16px;margin-top:20px;border-radius:8px;box-shadow:0 2px 6px rgba(0,0,0,0.1);}',
    'button{background:#222;color:#fff;border:none;padding:8px 14px;border-radius:6px;cursor:pointer;}',
  ],
  "server": [
    'const express=require("express"); const path=require("path"); const app=express(); app.use(express.json());',
    'app.use(express.static(__dirname));',
    'let cart=[]; let orders=[];',
    'app.get("/api/restaurants",(req,res)=>res.json({success:true,data:[]}));',
    'app.post("/api/cart/items",(req,res)=>{ cart.push(req.body); res.json({success:true,data:cart}); });',
    'app.get("/api/cart",(req,res)=>res.json({success:true,data:cart}));',
    'app.post("/api/orders",(req,res)=>{ const o={id:Date.now(),items:cart,total:req.body.total}; orders.push(o); cart=[]; res.json({success:true,data:o}); });',
    'app.get("/",(req,res)=>res.sendFile(path.join(__dirname,"fooddelivery.frontend.html")));',
    'app.listen(3000,()=>console.log("Food Delivery running"));',
  ],
 },
 5: {
  "frontend": [
    '<!DOCTYPE html><html><head><title>Classifieds</title>',
    '<link rel="stylesheet" href="classifieds.css"></head><body>',
    '<header><h1>Classifieds</h1></header>',
    '<div class="container">',
    '  <div class="add-product"><h2>Add Product</h2>',
    '    <input id="name" placeholder="Product name"><input id="price" placeholder="Price"><input id="seller" placeholder="Seller">',
    '    <textarea id="description" placeholder="Description"></textarea><button onclick="addProduct()">Add Product</button>',
    '  </div>',
    '  <div class="products"><h2>Available Products</h2><div id="products"></div></div>',
    '</div>',
    '<script src="classifieds.frontend.js"></script></body></html>',
    '',
    'let products=[{id:1,name:"iPhone 13",price:35000,seller:"Arun",description:"Good condition"}];',
    'function displayProducts(){',
    '  const list=document.getElementById("products"); list.innerHTML="";',
    '  products.forEach(p=>{',
    '    list.innerHTML+=`<div class="product"><h3>${p.name}</h3><p>Rs.${p.price}</p><p>${p.description}</p><button onclick="buyProduct(${p.id})">Contact Seller</button><button onclick="deleteProduct(${p.id})">Delete</button></div>`;',
    '  });',
    '}',
    'function addProduct(){',
    '  const name=document.getElementById("name").value; const price=document.getElementById("price").value;',
    '  if(!name||!price){alert("Fill all fields");return;}',
    '  products.push({id:Date.now(),name,price,seller:document.getElementById("seller").value,description:document.getElementById("description").value});',
    '  displayProducts();',
    '}',
    'function buyProduct(id){ const p=products.find(x=>x.id===id); alert("Seller: "+p.seller+"\\nProduct: "+p.name); }',
    'function deleteProduct(id){ products=products.filter(x=>x.id!==id); displayProducts(); }',
    'displayProducts();',
  ],
  "css": [
    'body{margin:0;font-family:Cambria;background:#f4f4f4;}',
    'header{background:#222;color:#fff;padding:16px;text-align:center;}',
    '.container{max-width:800px;margin:0 auto;padding:20px;}',
    '.add-product{background:#fff;padding:16px;border-radius:8px;margin-bottom:20px;}',
    'input,textarea{width:100%;padding:10px;margin:6px 0;border:1px solid #ccc;border-radius:6px;}',
    '.product{background:#fff;padding:16px;margin:10px 0;border-radius:8px;box-shadow:0 2px 6px rgba(0,0,0,0.1);}',
    'button{background:#222;color:#fff;border:none;padding:8px 14px;border-radius:6px;cursor:pointer;}',
  ],
  "server": [
    'const express=require("express"); const path=require("path"); const app=express(); app.use(express.json());',
    'app.use(express.static(__dirname));',
    'let products=[{id:1,name:"iPhone 13",price:35000}];',
    'app.get("/api/listings",(req,res)=>res.json({success:true,data:products}));',
    'app.post("/api/listings",(req,res)=>{ const p={id:Date.now(),...req.body}; products.push(p); res.json({success:true,data:p}); });',
    'app.delete("/api/listings/:id",(req,res)=>{ products=products.filter(x=>x.id!=req.params.id); res.json({success:true}); });',
    'app.get("/",(req,res)=>res.sendFile(path.join(__dirname,"classifieds.frontend.html")));',
    'app.listen(3000,()=>console.log("Classifieds running"));',
  ],
 },
 6: {
  "frontend": [
    '<!DOCTYPE html><html><head><title>Leave Management</title>',
    '<link rel="stylesheet" href="leave.css"></head><body>',
    '<header><h1>Leave Management</h1></header>',
    '<div class="container">',
    '  <div class="balance-card"><h2>Leave Balance</h2><p>Sick: <span id="sick">5</span> days</p><p>Casual: <span id="casual">5</span> days</p></div>',
    '  <div class="apply-leave"><h2>Apply for Leave</h2>',
    '    <select id="leaveType"><option>Sick Leave</option><option>Casual Leave</option></select>',
    '    <input type="date" id="fromDate"><input type="date" id="toDate"><textarea id="reason" placeholder="Reason"></textarea>',
    '    <button onclick="applyLeave()">Apply</button><p id="applyMessage"></p>',
    '  </div>',
    '  <div class="requests"><h2>My Requests</h2><div id="requestList"></div></div>',
    '</div>',
    '<script src="leave.frontend.js"></script></body></html>',
    '',
    'let requests=[];',
    'function applyLeave(){',
    '  const type=document.getElementById("leaveType").value;',
    '  const from=document.getElementById("fromDate").value;',
    '  const to=document.getElementById("toDate").value;',
    '  if(!from||!to){alert("Select dates");return;}',
    '  requests.push({id:Date.now(),type,from,to,status:"pending"});',
    '  showRequests();',
    '}',
    'function showRequests(){',
    '  const list=document.getElementById("requestList"); list.innerHTML="";',
    '  requests.forEach(r=>{ list.innerHTML+=`<div class="request"><b>${r.type}</b> ${r.from} to ${r.to} <span>${r.status}</span></div>`; });',
    '}',
  ],
  "css": [
    'body{margin:0;font-family:Cambria;background:#f4f4f4;}',
    'header{background:#222;color:#fff;padding:16px;text-align:center;}',
    '.container{max-width:700px;margin:0 auto;padding:20px;}',
    '.balance-card{background:#222;color:#fff;padding:16px;border-radius:8px;}',
    '.apply-leave{background:#fff;padding:16px;margin:16px 0;border-radius:8px;box-shadow:0 2px 6px rgba(0,0,0,0.1);}',
    'input,select,textarea{width:100%;padding:10px;margin:6px 0;border:1px solid #ccc;border-radius:6px;}',
    'button{background:#222;color:#fff;border:none;padding:8px 14px;border-radius:6px;cursor:pointer;}',
  ],
  "server": [
    'const express=require("express"); const path=require("path"); const app=express(); app.use(express.json());',
    'app.use(express.static(__dirname));',
    'let leaves=[];',
    'app.get("/api/leaves",(req,res)=>res.json({success:true,data:leaves}));',
    'app.post("/api/leaves",(req,res)=>{ const l={id:Date.now(),...req.body,status:"pending"}; leaves.push(l); res.json({success:true,data:l}); });',
    'app.delete("/api/leaves/:id",(req,res)=>{ leaves=leaves.filter(x=>x.id!=req.params.id); res.json({success:true}); });',
    'app.get("/api/leaves/balance",(req,res)=>res.json({success:true,data:{sick:5,casual:5}}));',
    'app.put("/api/admin/leaves/:id",(req,res)=>{ const l=leaves.find(x=>x.id==req.params.id); if(l) l.status=req.body.status; res.json({success:true,data:l}); });',
    'app.get("/",(req,res)=>res.sendFile(path.join(__dirname,"leave.frontend.html")));',
    'app.listen(3000,()=>console.log("Leave running"));',
  ],
 },
 7: {
  "frontend": [
    '<!DOCTYPE html><html><head><title>Project Management</title>',
    '<link rel="stylesheet" href="project.css"></head><body>',
    '<header><h1>Project Management</h1></header>',
    '<div class="container">',
    '  <div class="sidebar"><h2>Projects</h2><div id="projectList"></div><button onclick="addProject()">Add Project</button></div>',
    '  <div class="main"><div id="projectView"><h2 id="projTitle"></h2><div id="taskList"></div><button onclick="addTask()">Add Task</button></div></div>',
    '</div>',
    '<script src="project.frontend.js"></script></body></html>',
    '',
    'let projects=[{id:1,name:"Web App",tasks:[]}];',
    'function loadProjects(){',
    '  const list=document.getElementById("projectList"); list.innerHTML="";',
    '  projects.forEach(p=>{ list.innerHTML+=`<div class="project-item"><h3 onclick="openProject(${p.id})">${p.name}</h3><small>${p.tasks.length} tasks</small></div>`; });',
    '}',
    'function openProject(id){',
    '  const proj=projects.find(x=>x.id===id); document.getElementById("projTitle").innerText=proj.name;',
    '  const tl=document.getElementById("taskList"); tl.innerHTML="";',
    '  proj.tasks.forEach(t=>{ tl.innerHTML+=`<div class="task"><span>${t.title}</span><button onclick="toggleTask(${proj.id},${t.id})">Done</button></div>`; });',
    '}',
    'function addTask(){ const title=prompt("Enter task:"); if(!title) return; projects[0].tasks.push({id:Date.now(),title,done:false}); openProject(projects[0].id); }',
    'loadProjects();',
  ],
  "css": [
    'body{margin:0;font-family:Cambria;background:#f4f4f4;}',
    'header{background:#222;color:#fff;padding:16px;text-align:center;}',
    '.container{display:grid;grid-template-columns:250px 1fr;gap:20px;max-width:1000px;margin:0 auto;padding:20px;}',
    '.sidebar{background:#fff;padding:16px;border-radius:8px;}',
    '.main{background:#fff;padding:16px;border-radius:8px;}',
    '.project-item{padding:10px;border-bottom:1px solid #eee;cursor:pointer;}',
    '.task{display:flex;justify-content:space-between;padding:8px;border-bottom:1px solid #eee;}',
    'button{background:#222;color:#fff;border:none;padding:8px 14px;border-radius:6px;cursor:pointer;}',
  ],
  "server": [
    'const express=require("express"); const path=require("path"); const app=express(); app.use(express.json());',
    'app.use(express.static(__dirname));',
    'let projects=[{id:1,name:"Web App",tasks:[]}];',
    'app.get("/api/projects",(req,res)=>res.json({success:true,data:projects}));',
    'app.post("/api/projects",(req,res)=>{ const p={id:Date.now(),...req.body,tasks:[]}; projects.push(p); res.json({success:true,data:p}); });',
    'app.get("/api/tasks",(req,res)=>res.json({success:true,data:projects[0].tasks}));',
    'app.post("/api/tasks",(req,res)=>{ const t={id:Date.now(),...req.body}; projects[0].tasks.push(t); res.json({success:true,data:t}); });',
    'app.get("/",(req,res)=>res.sendFile(path.join(__dirname,"project.frontend.html")));',
    'app.listen(3000,()=>console.log("Project running"));',
  ],
 },
 8: {
  "frontend": [
    '<!DOCTYPE html><html><head><title>Online Survey</title>',
    '<link rel="stylesheet" href="survey.css"></head><body>',
    '<header><h1>Online Survey</h1></header>',
    '<div class="container">',
    '  <div id="surveyStart"><h2>Select a Survey</h2><button onclick="startSurvey()">Start Survey</button></div>',
    '  <div id="surveyForm" style="display:none;"><h2 id="questionText"></h2><div id="options"></div><button onclick="nextQuestion()">Next</button></div>',
    '  <div id="result" style="display:none;"><h2>Survey Completed</h2><p id="scoreText"></p></div>',
    '</div>',
    '<script src="survey.frontend.js"></script></body></html>',
    '',
    'let questions=[{id:1,text:"What is your favorite language?",options:["HTML","CSS","JS","Python"],correct:2},{id:2,text:"Is JS object-oriented?",options:["True","False"],correct:0}];',
    'let currentQ=0; let score=0;',
    'function startSurvey(){ document.getElementById("surveyStart").style.display="none"; document.getElementById("surveyForm").style.display="block"; showQuestion(); }',
    'function showQuestion(){',
    '  const q=questions[currentQ]; document.getElementById("questionText").innerText=q.text;',
    '  const div=document.getElementById("options"); div.innerHTML="";',
    '  q.options.forEach((opt,i)=>{ div.innerHTML+=`<label><input type="radio" name="ans" value="${i}"> ${opt}</label>`; });',
    '}',
    'function nextQuestion(){',
    '  const sel=document.querySelector(\'input[name="ans"]:checked\'); if(!sel){alert("Select option");return;}',
    '  if(parseInt(sel.value)===questions[currentQ].correct) score++;',
    '  currentQ++; if(currentQ>=questions.length) showResult(); else showQuestion();',
    '}',
    'function showResult(){ document.getElementById("surveyForm").style.display="none"; document.getElementById("result").style.display="block"; document.getElementById("scoreText").innerText="Score: "+score+"/"+questions.length; }',
  ],
  "css": [
    'body{margin:0;font-family:Cambria;background:#f4f4f4;}',
    'header{background:#222;color:#fff;padding:16px;text-align:center;}',
    '.container{max-width:700px;margin:0 auto;padding:20px;}',
    '#surveyForm{background:#fff;padding:20px;border-radius:8px;box-shadow:0 2px 6px rgba(0,0,0,0.1);}',
    'label{display:block;padding:8px;margin:6px 0;background:#f5f5f5;border-radius:6px;cursor:pointer;}',
    'label:hover{background:#e8f0fe;}',
    'button{background:#222;color:#fff;border:none;padding:8px 14px;border-radius:6px;cursor:pointer;}',
  ],
  "server": [
    'const express=require("express"); const path=require("path"); const app=express(); app.use(express.json());',
    'app.use(express.static(__dirname));',
    'let questions=[{id:1,text:"What is favorite language?",options:["HTML","CSS","JS"],correct:2}]; let attempts=[];',
    'app.get("/api/questions",(req,res)=>res.json({success:true,data:questions}));',
    'app.post("/api/questions",(req,res)=>{ const q={id:Date.now(),...req.body}; questions.push(q); res.json({success:true,data:q}); });',
    'app.put("/api/questions/:id",(req,res)=>{ const q=questions.find(x=>x.id==req.params.id); if(q) Object.assign(q,req.body); res.json({success:true,data:q}); });',
    'app.delete("/api/questions/:id",(req,res)=>{ questions=questions.filter(x=>x.id!=req.params.id); res.json({success:true}); });',
    'app.post("/api/survey/start",(req,res)=>{ const a={id:Date.now(),questions:questions.slice(0,5),score:0}; attempts.push(a); res.json({success:true,data:a}); });',
    'app.post("/api/survey/submit",(req,res)=>{ let s=0; req.body.answers.forEach(a=>{ const q=questions.find(x=>x.id==a.qId); if(q&&q.correct==a.value) s++; }); res.json({success:true,data:{score:s,total:questions.length}}); });',
    'app.get("/api/survey/history",(req,res)=>res.json({success:true,data:attempts}));',
    'app.get("/api/survey/:id",(req,res)=>{ const a=attempts.find(x=>x.id==req.params.id); res.json({success:true,data:a}); });',
    'app.get("/api/health",(req,res)=>res.json({status:"ok",database:"connected"}));',
    'app.use((req,res)=>res.status(404).json({success:false,message:"Route not found"}));',
    'app.get("/",(req,res)=>res.sendFile(path.join(__dirname,"survey.frontend.html")));',
    'app.listen(3000,()=>console.log("Survey running at http://localhost:3000"));',
  ],
 },
}

def add_code(doc, label, lines):
    p = doc.add_paragraph()
    r = p.add_run(label); r.bold = True; r.font.size = Pt(12); r.font.name = "Cambria"
    p.paragraph_format.space_before = Pt(10); p.paragraph_format.space_after = Pt(6)
    p2 = doc.add_paragraph()
    p2.paragraph_format.space_before = Pt(0); p2.paragraph_format.space_after = Pt(8); p2.paragraph_format.line_spacing = Pt(22)
    for line in lines:
        r = p2.add_run(line + "\n"); r.font.name = "Cambria"; r.font.size = Pt(12)

doc = Document()
style = doc.styles["Normal"]; style.font.name = "Cambria"; style.font.size = Pt(10)

for _ in range(4): doc.add_paragraph("")
t = doc.add_paragraph(); t.alignment = 1; r = t.add_run("Full Stack Web Lab — Experiments 2 to 8"); r.bold = True; r.font.size = Pt(22); r.font.name = "Cambria"
s = doc.add_paragraph(); s.alignment = 1; r = s.add_run("Single Source per Experiment"); r.bold = True; r.font.size = Pt(14); r.font.name = "Cambria"
doc.add_paragraph("")
info = doc.add_paragraph(); info.alignment = 1; r = info.add_run("One Frontend + One CSS + One Server file per experiment\nFont: Cambria 12pt (headings) / 10pt (code)"); r.font.size = Pt(12); r.font.name = "Cambria"
doc.add_page_break()

for num, key, title, desc in EXPS:
    h = doc.add_paragraph(); h.alignment = 1
    r = h.add_run(f"EXPERIMENT {num}"); r.bold = True; r.font.size = Pt(18); r.font.name = "Cambria"
    h2 = doc.add_paragraph(); h2.alignment = 1
    r = h2.add_run(title); r.bold = True; r.font.size = Pt(14); r.font.name = "Cambria"
    p = doc.add_paragraph(); p.alignment = 1
    r = p.add_run(desc); r.italic = True; r.font.size = Pt(12); r.font.name = "Cambria"
    doc.add_paragraph("")
    p = doc.add_paragraph(); p.alignment = 2; r = p.add_run("9665"); r.bold = True; r.font.size = Pt(12); r.font.name = "Cambria"
    doc.add_paragraph("")
    p = doc.add_paragraph(); r = p.add_run("PROGRAM :"); r.bold = True; r.font.size = Pt(12); r.font.name = "Cambria"
    doc.add_paragraph("")

    c = CODE[num]
    add_code(doc, f"{key}.frontend  (HTML + JS)", c["frontend"])
    for _ in range(15): doc.add_paragraph("")
    add_code(doc, f"{key}.CSS", c["css"])
    for _ in range(15): doc.add_paragraph("")
    add_code(doc, f"{key}.server  (server.js)", c["server"])
    for _ in range(15): doc.add_paragraph("")

    p = doc.add_paragraph(); r = p.add_run("OUTPUT :"); r.bold = True; r.font.size = Pt(12); r.font.name = "Cambria"
    for _ in range(420): doc.add_paragraph("")
    p = doc.add_paragraph(); r = p.add_run("RESULT :"); r.bold = True; r.font.size = Pt(12); r.font.name = "Cambria"
    doc.add_paragraph("")
    doc.add_page_break()

out = OUT / "All_Experiments_2_to_8_Single_Source.docx"
doc.save(str(out))
print(f"Generated: {out.name}")
